### ISSUE TITLE
Ordenar los departamentos

### ISSUE THREAD

**Issue by carlosal1015** [lilberick/TelegramBotCovid#1]
![image](https://user-images.githubusercontent.com/21283014/84606105-75898500-ae68-11ea-9cda-8e4673afc7ec.png)

Recordatorio para no olvidar ordenar los departamentos.

**Comment by lilberick** [comment]
**Listo, ya lo he solucionado, ahora coincide la columna "Departamento" y "Departamentos"**  

![1](https://user-images.githubusercontent.com/20149673/85930529-c5ae1180-b882-11ea-9d33-1ef6a49fc356.png)
![2](https://user-images.githubusercontent.com/20149673/85930531-c9419880-b882-11ea-87db-63cdb8f492e0.png)
